config/routes.rb
Rails.application.routes.draw do
	root "items#index"

	resources :items, only: [:show, :index] do
		resources :cart_items, only: [:create, :destroy]
		resources :image_urls, only: [:create]
	end
	devise_for :users
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	resources :users, only: [:show] do
		resources :carts, only: [:show] do
			resources :orders, only: [:create, :show]
		end
	end
	resources :charges


	scope 'admin', module: 'admin', as: 'admin' do
		resources :items
		resources :orders, only: [:index, :show]
	end



	get "/statics/:static" => "statics#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user
    has_many :cart_items
    has_many :items, through: :cart_items

		def price_sum
			sum = 0
			self.items.each do |each_item|
				sum += each_item.price
			end
			return sum
		end

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :item
    belongs_to :cart

end

app/models/item.rb
class Item < ApplicationRecord    
    validates :title, 
    presence: true
    validates_length_of :title,
    minimum: 5


    validates :description, 
    presence: true
    validates_length_of :description,
    minimum: 10
    
    validates :price, 
    presence: true,
    numericality: {greater_than_or_equal_to: 5}

    validates :image_url, 
    presence: true

    has_many :cart_items, dependent: :destroy
    has_many :carts, through: :cart_items 

		has_many :order_items, dependent: :destroy
		has_many :orders, through: :order_items
    
    has_one_attached :image_url 

		def orders_qty
			qty = self.orders.count
		end

		def self.best_item
			best_item = Item.first
			max_boughts = Item.first.orders_qty
			self.all.each do |each_item|
				if each_item.orders_qty > max_boughts
					max_boughts = each_item.orders_qty
					best_item = each_item
				end
			end
			return best_item
		end

end

app/models/order.rb
class Order < ApplicationRecord
	after_create :command_send
	after_create :admin_send
	belongs_to :user
	has_many :order_items, dependent: :destroy
	has_many :items, through: :order_items

	def command_send
		UserMailer.command_email(self).deliver_now
	end

	def admin_send
		AdminMailer.order_email(self).deliver_now
	end

	def price_sum
		sum = 0
		self.items.each do |each_item|
			sum += each_item.price
		end
		return sum 
	end

	def self.ca
		ca = 0
		Order.all.each do |each_order|
			ca += each_order.price_sum	
		end
		return ca
	end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :order
	belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  after_create :create_cart
  after_create :welcome_send
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one :cart, dependent: :destroy
	has_many :orders


  def create_cart
    @cart = Cart.new(id: self.id, user: self)
    @cart.save
    self.cart = @cart
    self.save
  end

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

	def orders_qty
		qty = self.orders.count
	end

	def self.best_buyer
		best_buyer = User.first
		max_boughts = User.first.orders_qty
		self.all.each do |each_user|
			if each_user.orders_qty > max_boughts
				max_boughts = each_user.orders_qty
				best_buyer = each_user
			end
		end
		return best_buyer
	end

end

app/controllers/admin/items_controller.rb
module Admin
	class ItemsController < ApplicationController
#		before_action :require_admin

		def index
			@items = Item.all
		end

		def new 
			@item = Item.new
		end 

		def create
			puts params
			item_params = params[:item]
			@item = Item.new(title: item_params[:title], description: item_params[:description], price: item_params[:price].to_i)
			if @item.save	
				flash[:success] = "Item created"
				redirect_to admin_items_path
			else
				flash[:danger] = "Item NOT created, please check your params"
				puts @item.errors.messages
				redirect_to new_admin_item_path
			end
		end 

		def destroy
			puts params
			@item = Item.find(params[:id])
			@item.destroy
		end

		private

		def require_admin
			unless isAdmin?
				flash[:error] = "Vous devez etre Administrateur pour repertorier une photo"
				redirect_to root_path
			end
		end
	end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  
  def show
    @cart = Cart.find(params[:id])
		@price_sum = @cart.price_sum 

  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	def new
		@cart = current_user.cart
		@amount = @cart.price_sum * 100
	end

	def create

		# Amounts in cents
		@cart = current_user.cart
		@amount = @cart.price_sum * 100

		customer = Stripe::Customer.create({
			email: params[:stripeEmail],
			source: params[:stripeToken],
		})

		charge = Stripe::Charge.create({
			customer: customer.id,
			amount: @amount.to_i,
			description: 'Rails Stripe customer',
			currency: 'eur',
		})

		if charge
			@order = Order.new
			@order.user = current_user
			@order.save
			@cart = current_user.cart
			@cart.items.each do |each_item|
				order_item = OrderItem.new
				order_item.item = each_item
				order_item.order = @order
				order_item.save
			end
			CartItem.where(cart: @cart).destroy_all
		else
			flash[:error] = "Probleme lors de la creation de la commande ou lors du paiement."
			redirect_to user_cart_path(current_user.id, current_user.cart.id)
		end

	rescue Stripe::CardError => e
		flash[:error] = e.message
		redirect_to new_user_cart_charge_path
	end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

	def index
		@items = Item.all
	end

	def show
		@item = Item.find(params[:id])
	end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	before_action :authenticate_user!

	def show
		puts params	
	end


end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
    def show
        render template: "statics/#{params[:static]}"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	
	def show
		puts params
		@user = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/image_urls_helper.rb
module ImageUrlsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/permission_helper.rb
module PermissionHelper
	
	def isAdmin?
		user_signed_in? && current_user.role == 'admin'
	end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/items/index.html.erb
<%= flash[:success] %>
<%= flash[:danger] %>

<h1>Gestion des Items</h1>

<table class="table table-striped">

	<thead>
		<tr>
			<th>Photo</th>
			<th>Titre </th>
			<th>Prix</th>
			<th class="text-center">Actions</th>
		</tr>
	</thead>
	<tbody>

		<% @items.each do |each_item| %>
			<tr>
				<td>
					<%if each_item.image_url.attached?%>
						<%= image_tag each_item.image_url, alt: 'image', style: "height: 50px; width: auto; display: block;" %>
					<%else%>
						<img style="height: 50px; width: auto; display: block;" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22318%22%20height%3D%22180%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20318%20180%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_158bd1d28ef%20text%20%7B%20fill%3Argba(255%2C255%2C255%2C.75)%3Bfont-weight%3Anormal%3Bfont-family%3AHelvetica%2C%20monospace%3Bfont-size%3A16pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_158bd1d28ef%22%3E%3Crect%20width%3D%22318%22%20height%3D%22180%22%20fill%3D%22%23777%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%22129.359375%22%20y%3D%2297.35%22%3EImage%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" alt="Card image">
					<%end%>
				</td>	
				<td><%= each_item.title %></td>
				<td><%= each_item.price %></td>
				<td>
					<%= link_to 'Supprimer', [:admin, each_item], class: 'btn btn-sm btn-danger', data: {method: 'delete', confirm: 'Are you sure ?' } %>
				</td>
				<td>
					<%= form_tag item_image_urls_path(each_item.id),  multipart: true do %>
						<span class= "btn btn-large btn-warning btn-file btn-sm">
							Choose File
							<%= file_field_tag :image_url %>
						</span>
				</td>
				<td>
					<%= submit_tag "Uploader Photo", class: "btn btn-primary btn-sm" %>
				<% end %>
				</td>

			</tr>
		<% end %>

	</tbody>
</table>

<%= link_to "Ajouter un Item", new_admin_item_path, class: 'btn btn-block btn-success' %>

app/views/admin/items/new.html.erb
<div class="container py-3">
	<h2 class="font-weight-bold text-center my-4">Créer un Item</h2>

	<%=form_for @item, url: {action: "create"}, html: {class: "list-group"} do |f|%>

		<div class="form-group">
			<%= f.label :title, "Titre"%> 
			<%= f.text_field :title, class: "form-control list-group-item"%>
		</div>

		<div class="form-group">
			<%= f.label :description, "Description" %>
			<%= f.text_area :description, class: "form-control list-group-item" %>
		</div>

		<div class="form-group">
			<%= f.label :price, "Prix"%> 
			<%= f.text_field :price, class: "form-control list-group-item"%>
		</div>

		<div class="form-group">
			<button type="submit" class="btn btn-success btn-block">Créer l'Item</button>
		</div>

	<%end%>

</div>

app/views/items/index.html.erb
<div class="jumbotron md-12">
  <h1 class="display-3 text-dark">E-KITTY</h1>
  <p class="lead text-dark">On a tant à partager !</p>
  <hr class="my-4 text-dark">
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
  </p>
</div>
    <div class="row">
      <% @items.each do |item| %>
      <div class="col-md-3 col-sm-6 my-2">
        <div class="card border-0 shadow"  >
          <%if item.image_url.attached?%>
           <%= image_tag item.image_url, alt: 'image', class: "card-img-top kitty"%>
          <%else%>
           <%= image_tag "https://dummyimage.com/170x/000/fff&text=Test", alt: 'image', class: "card-img-top kitty"  %>
          <% end %>
          <div class="card-body text-center">
            <h5 class="card-title nowrap"> <%= item.title.truncate(15) %> </h5>
            <small class="card-text text-center"> <%= item.price.to_i %> € </small>
            <br />
            <a href="<%= item_path(item.id)%>" class="btn btn-primary"> Voir la photo </a>

          </div>
        </div>
        </div>
      <% end %>
    </div>
  

app/views/items/new.html.erb
<h2>Items#show</h2>

<p> formulaire d'ajout d'item </p>

app/views/items/show.html.erb
<div class = "container md-10 mb-5 card p-0 border-0"> 
	<h3 class= "card-header bg-secondary border text-white border "> <%=@item.title%> </h3>
	<div class="row justify-content-center">
		<div class = "col-md-6 mt-5">
		
			<div class="card-body bg-white">
				<h5 class="card-title bg-white">British Longhair</h5>
				<h6 class="card-subtitle text-muted">Chat mignon</h6>
			</div>
			<div class="card-body bg-white">
				<p class="card-text"><%=@item.description%></p>
			</div>
			<ul class="list-group list-group-flush">
				<li class="list-group-item"><%=@item.price%> €</li>
			</ul>
			<div class="card-body bg-white">
				<a href="https://www.croquetteland.com/fr/blog/chat/leducation-du-british-shorthair/" class="card-link">Education</a>
				<a href="https://www.whiskas.fr/nos-produits/chats-1-an-et-plus?gclid=Cj0KCQjw0pfzBRCOARIsANi0g0tfn04ysFB1II6okU4NHO6qp-w_SSxRmweh_USkFGVdQYWcn7nGzvsaAls6EALw_wcB" class="card-link">Nourir ton chat</a>
			</div>
	
		</div>
		<div class = "col-md-4 ml-4 mt-5 mr-0">
			<%# <img style="height: 300px; width: 100%; display: block;" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22318%22%20height%3D%22180%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20318%20180%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_158bd1d28ef%20text%20%7B%20fill%3Argba(255%2C255%2C255%2C.75)%3Bfont-weight%3Anormal%3Bfont-family%3AHelvetica%2C%20monospace%3Bfont-size%3A16pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_158bd1d28ef%22%3E%3Crect%20width%3D%22318%22%20height%3D%22180%22%20fill%3D%22%23777%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%22129.359375%22%20y%3D%2297.35%22%3EImage%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" alt="Card image">%>
			<%if @item.image_url.attached?%>
				<%= image_tag @item.image_url, alt: 'image', style: "height: 300px; width: 100%; display: block;" %>
			<%else%>
				<img style="height: 300px; width: 100%; display: block;" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22318%22%20height%3D%22180%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20318%20180%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_158bd1d28ef%20text%20%7B%20fill%3Argba(255%2C255%2C255%2C.75)%3Bfont-weight%3Anormal%3Bfont-family%3AHelvetica%2C%20monospace%3Bfont-size%3A16pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_158bd1d28ef%22%3E%3Crect%20width%3D%22318%22%20height%3D%22180%22%20fill%3D%22%23777%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%22129.359375%22%20y%3D%2297.35%22%3EImage%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" alt="Card image">
			<%end%>

			<% if isAdmin? %>
				<%= form_tag item_image_urls_path(@item),  multipart: true do %>
					<span class= "btn btn-large btn-warning btn-file">
						Choose File
						<%= file_field_tag :image_url %>
					</span>
					<%= submit_tag "Uploader l'image", class: "btn btn-primary mb-4 mt-4" %>
				<% end %>
			<% end %>
			<br/>
			<%= link_to 'Ajouter au panier',  item_cart_items_path(@item.id), method: 'post',  class: "btn btn-secondary float-center" %>
       <br/> <br/>
			<div><%= flash[:success] %></div>
			<div><%= flash[:warning] %></div>

 

 
		</div>

	</div>
</div>