config/routes.rb
Rails.application.routes.draw do
	root "items#index"

	resources :items, only: [:show, :index] do
		resources :cart_items, only: [:create, :destroy]
		resources :image_urls, only: [:create]
	end
	devise_for :users
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	resources :users, only: [:show] do
		resources :carts, only: [:show] do
			resources :orders, only: [:create, :show]
		end
	end
	resources :charges


	scope 'admin', module: 'admin', as: 'admin' do
		resources :items
		resources :orders, only: [:index, :show]
	end



	get "/statics/:static" => "statics#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user
    has_many :cart_items
    has_many :items, through: :cart_items

		def price_sum
			sum = 0
			self.items.each do |each_item|
				sum += each_item.price
			end
			return sum
		end

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :item
    belongs_to :cart

end

app/models/item.rb
class Item < ApplicationRecord    
    validates :title, 
    presence: true
    validates_length_of :title,
    minimum: 5


    validates :description, 
    presence: true
    validates_length_of :description,
    minimum: 10
    
    validates :price, 
    presence: true,
    numericality: {greater_than_or_equal_to: 5}

    validates :image_url, 
    presence: true

    has_many :cart_items, dependent: :destroy
    has_many :carts, through: :cart_items 

		has_many :order_items, dependent: :destroy
		has_many :orders, through: :order_items
    
    has_one_attached :image_url 

		def orders_qty
			qty = self.orders.count
		end

		def self.best_item
			best_item = Item.first
			max_boughts = Item.first.orders_qty
			self.all.each do |each_item|
				if each_item.orders_qty > max_boughts
					max_boughts = each_item.orders_qty
					best_item = each_item
				end
			end
			return best_item
		end

end

app/models/order.rb
class Order < ApplicationRecord
	after_create :command_send
	after_create :admin_send
	belongs_to :user
	has_many :order_items, dependent: :destroy
	has_many :items, through: :order_items

	def command_send
		UserMailer.command_email(self).deliver_now
	end

	def admin_send
		AdminMailer.order_email(self).deliver_now
	end

	def price_sum
		sum = 0
		self.items.each do |each_item|
			sum += each_item.price
		end
		return sum 
	end

	def self.ca
		ca = 0
		Order.all.each do |each_order|
			ca += each_order.price_sum	
		end
		return ca
	end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :order
	belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  after_create :create_cart
  after_create :welcome_send
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one :cart, dependent: :destroy
	has_many :orders


  def create_cart
    @cart = Cart.new(id: self.id, user: self)
    @cart.save
    self.cart = @cart
    self.save
  end

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

	def orders_qty
		qty = self.orders.count
	end

	def self.best_buyer
		best_buyer = User.first
		max_boughts = User.first.orders_qty
		self.all.each do |each_user|
			if each_user.orders_qty > max_boughts
				max_boughts = each_user.orders_qty
				best_buyer = each_user
			end
		end
		return best_buyer
	end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  
  def show
    @cart = Cart.find(params[:id])
		@price_sum = @cart.price_sum 

  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	def new
		@cart = current_user.cart
		@amount = @cart.price_sum * 100
	end

	def create

		# Amounts in cents
		@cart = current_user.cart
		@amount = @cart.price_sum * 100

		customer = Stripe::Customer.create({
			email: params[:stripeEmail],
			source: params[:stripeToken],
		})

		charge = Stripe::Charge.create({
			customer: customer.id,
			amount: @amount.to_i,
			description: 'Rails Stripe customer',
			currency: 'eur',
		})

		if charge
			@order = Order.new
			@order.user = current_user
			@order.save
			@cart = current_user.cart
			@cart.items.each do |each_item|
				order_item = OrderItem.new
				order_item.item = each_item
				order_item.order = @order
				order_item.save
			end
			CartItem.where(cart: @cart).destroy_all
		else
			flash[:error] = "Probleme lors de la creation de la commande ou lors du paiement."
			redirect_to user_cart_path(current_user.id, current_user.cart.id)
		end

	rescue Stripe::CardError => e
		flash[:error] = e.message
		redirect_to new_user_cart_charge_path
	end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

	def index
		@items = Item.all
	end

	def show
		@item = Item.find(params[:id])
	end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	before_action :authenticate_user!

	def show
		puts params	
	end


end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
    def show
        render template: "statics/#{params[:static]}"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	
	def show
		puts params
		@user = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/image_urls_helper.rb
module ImageUrlsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/permission_helper.rb
module PermissionHelper
	
	def isAdmin?
		user_signed_in? && current_user.role == 'admin'
	end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/show.html.erb
<br />
<br />
<h1 class="text-center"> Voici votre panier !</h1>
<br />
<br />
<div class="card-body">
  <% if @cart.cart_items.first %>
    <% @cart.items.uniq.each do |item|%>
      <div class="row">
        <div class="col-12 col-sm-12 col-md-2 text-center">
          <img class="img-responsive" src="http://placehold.it/120x80" alt="prewiew" width="120" height="80">
        </div>
        <div class="col-12 text-sm-center col-sm-12 text-md-left col-md-6">
          <h4 class="product-name"><strong> <%= item.title %> </strong></h4>
          <small> <%= item.description %></small>
        </div>
        <div class="col-12 col-sm-12 text-sm-center col-md-4 text-md-right row">
        
          <div class="col-3 col-sm-3 col-md-6 text-md-right" style="padding-top: 5px">
          <% if CartItem.where(cart: @cart, item: item).count > 1 %>
            <%= link_to '-', item_cart_item_path(item.id, CartItem.where(cart: @cart, item: item).last.id), class: "btn btn-outline-danger mx-2", method: 'delete' %>
          <% end %>
            <strong class="color-primary"><%= CartItem.where(cart: @cart, item: item).count %></strong>
            <%= link_to '+', item_cart_items_path(item.id), class: "btn btn-outline-success mx-2", method: 'post'  %>
            <h6><strong> Price : <%= CartItem.where(cart: @cart, item: item).count * item.price %> €</strong> </h6>
          </div>
          <% if CartItem.where(cart: @cart, item: item).count == 1 %>
            <div class="col-3 col-sm-2 col-md-2 text-right">
            <%= link_to "Supprimer du Panier", item_cart_item_path(item.id, item.cart_items.first.id), method: "delete", class: "btn btn-outline-danger" %>
          </div>
          <% end %>
          
        </div>
      </div>
    </div>
    <hr>
  <% end %>
  <div class="text-right mr-5 ml-5">
  	<h5 class=" ">Prix Total :  &nbsp;    <span style = "color:grey"><%= @price_sum %>  euros</h5> </span><br/><br/>
		<%= link_to "PASSER COMMANDE STRIPE", new_charge_path, class: "btn btn-secondary btn-block  d-flex align-items-center justify-content-center", style: "height:50px" %>
	
	<% else %>
    
		<h5 class= "text-center">Votre panier ne contient aucune photo...</h5>
     <br/> <br/> <br/> <br/> <br/> 
	<% end %>

  </div>
</div>

app/views/users/show.html.erb
	<div class = "container mb-5"> 
		<div class="row">
			<div class = "col-md-7 card border-0 shadow p-0">
				<h3 class= "card-header bg-primary text-white border-0"> <%= @user.id %> </h3>
				<div class="card-body bg-white">
					<h5 class="card-title"> <%= @user.email %> </h5>
					<hr>
					<h6 class="card-subtitle text-muted"> Cat lover</h6>
				</div>
				
				<div class="card-body bg-white">
					<h6 class="card-text text-muted card-subtitle"> <%= %> Description:</h6>
				</div>
				<div class="card-body bg-white">
					<a href="<%= edit_user_registration_path %>" type="button" class="btn btn-warning mt-5">Editer le profil</a>
					<a href="<%= user_cart_path(@user.id, @user.cart.id) %>" type="button" class="btn btn-primary mt-5">Voir mon Panier</a>
				</div>
				<div class="card-footer text-muted bg-white">
					2 days ago
				</div>
			</div>
				<div class = "col-md-5 text-center ">
				<img style="height: 300px; width: 100%; display: block;" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22318%22%20height%3D%22180%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20318%20180%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_158bd1d28ef%20text%20%7B%20fill%3Argba(255%2C255%2C255%2C.75)%3Bfont-weight%3Anormal%3Bfont-family%3AHelvetica%2C%20monospace%3Bfont-size%3A16pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_158bd1d28ef%22%3E%3Crect%20width%3D%22318%22%20height%3D%22180%22%20fill%3D%22%23777%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%22129.359375%22%20y%3D%2297.35%22%3EImage%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" alt="Card image">
				</div>
				
		</div>
	</div>

	<div class="container md-11 p-0 card border bg-white">

		<h3 class="card-header border bg-white">Historique des Commandes</h3>
		<div class="list-group">
			<% @user.orders.each do |each_order| %>

				<div class="list-group-item">
					<div class="row">

						<div class="col-4">
							<%= each_order.items.count %> photos achetées
						</div>

						<div class="col-4 text-center">
						Prix Total : <%= each_order.price_sum.to_i%> €
						</div>

						<div class="col-4 text-right">
							Date : <%= each_order.updated_at %>
						</div>
					</div>

				</div>

			<% end %>
		</div>
	</div>