config/routes.rb
Rails.application.routes.draw do
	root "items#index"

	resources :items, only: [:show, :index] do
		resources :cart_items, only: [:create, :destroy]
		resources :image_urls, only: [:create]
	end
	devise_for :users
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	resources :users, only: [:show] do
		resources :carts, only: [:show] do
			resources :orders, only: [:create, :show]
		end
	end
	resources :charges


	scope 'admin', module: 'admin', as: 'admin' do
		resources :items
		resources :orders, only: [:index, :show]
	end



	get "/statics/:static" => "statics#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user
    has_many :cart_items
    has_many :items, through: :cart_items

		def price_sum
			sum = 0
			self.items.each do |each_item|
				sum += each_item.price
			end
			return sum
		end

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :item
    belongs_to :cart

end

app/models/item.rb
class Item < ApplicationRecord    
    validates :title, 
    presence: true
    validates_length_of :title,
    minimum: 5


    validates :description, 
    presence: true
    validates_length_of :description,
    minimum: 10
    
    validates :price, 
    presence: true,
    numericality: {greater_than_or_equal_to: 5}

    validates :image_url, 
    presence: true

    has_many :cart_items, dependent: :destroy
    has_many :carts, through: :cart_items 

		has_many :order_items, dependent: :destroy
		has_many :orders, through: :order_items
    
    has_one_attached :image_url 

		def orders_qty
			qty = self.orders.count
		end

		def self.best_item
			best_item = Item.first
			max_boughts = Item.first.orders_qty
			self.all.each do |each_item|
				if each_item.orders_qty > max_boughts
					max_boughts = each_item.orders_qty
					best_item = each_item
				end
			end
			return best_item
		end

end

app/models/order.rb
class Order < ApplicationRecord
	after_create :command_send
	after_create :admin_send
	belongs_to :user
	has_many :order_items, dependent: :destroy
	has_many :items, through: :order_items

	def command_send
		UserMailer.command_email(self).deliver_now
	end

	def admin_send
		AdminMailer.order_email(self).deliver_now
	end

	def price_sum
		sum = 0
		self.items.each do |each_item|
			sum += each_item.price
		end
		return sum 
	end

	def self.ca
		ca = 0
		Order.all.each do |each_order|
			ca += each_order.price_sum	
		end
		return ca
	end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :order
	belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  after_create :create_cart
  after_create :welcome_send
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one :cart, dependent: :destroy
	has_many :orders


  def create_cart
    @cart = Cart.new(id: self.id, user: self)
    @cart.save
    self.cart = @cart
    self.save
  end

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

	def orders_qty
		qty = self.orders.count
	end

	def self.best_buyer
		best_buyer = User.first
		max_boughts = User.first.orders_qty
		self.all.each do |each_user|
			if each_user.orders_qty > max_boughts
				max_boughts = each_user.orders_qty
				best_buyer = each_user
			end
		end
		return best_buyer
	end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  
  def show
    @cart = Cart.find(params[:id])
		@price_sum = @cart.price_sum 

  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	def new
		@cart = current_user.cart
		@amount = @cart.price_sum * 100
	end

	def create

		# Amounts in cents
		@cart = current_user.cart
		@amount = @cart.price_sum * 100

		customer = Stripe::Customer.create({
			email: params[:stripeEmail],
			source: params[:stripeToken],
		})

		charge = Stripe::Charge.create({
			customer: customer.id,
			amount: @amount.to_i,
			description: 'Rails Stripe customer',
			currency: 'eur',
		})

		if charge
			@order = Order.new
			@order.user = current_user
			@order.save
			@cart = current_user.cart
			@cart.items.each do |each_item|
				order_item = OrderItem.new
				order_item.item = each_item
				order_item.order = @order
				order_item.save
			end
			CartItem.where(cart: @cart).destroy_all
		else
			flash[:error] = "Probleme lors de la creation de la commande ou lors du paiement."
			redirect_to user_cart_path(current_user.id, current_user.cart.id)
		end

	rescue Stripe::CardError => e
		flash[:error] = e.message
		redirect_to new_user_cart_charge_path
	end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

	def index
		@items = Item.all
	end

	def show
		@item = Item.find(params[:id])
	end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	before_action :authenticate_user!

	def show
		puts params	
	end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	
	def show
		puts params
		@user = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/image_urls_helper.rb
module ImageUrlsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/permission_helper.rb
module PermissionHelper
	
	def isAdmin?
		user_signed_in? && current_user.role == 'admin'
	end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/charges/create.html.erb
<div class= "container card border-0">
    <div class="card-body m-4 text-center">
      <h2>Merci, vous avez pay&eacute; <strong> <%= @amount / 100 %>&euro;</strong>!</h2>



      <h3>Votre commande est CONFIRM&Eacute;E</h3>
      <p>Vous recevrez un e-mail de confirmation sur <%= current_user.email %>
      <hr>
        <h3>RECAP DE LA COMMANDE</h3>
        <% @cart.items.each do |each_item| %>
          <div><%= each_item.title %></div>
          <div><%= each_item.price %> </div>
        <% end %>
      </div>

      <%= link_to "Revenir au Profil", user_path(current_user.id), class: "btn btn-secondary btn-block" %>
</div>

app/views/charges/new.html.erb
<br/>
<br/>

		<div class=" card container-fluid col-md-8 p-0  shadow">

		<div class="card-header bg-secondary text-white ">
			<h2 class="text-center"> Récapitulatif de votre commande: </h2>
		</div>
			<div class = "card-body">
				<%= form_tag charges_path do %>
					<% @cart.items.each do |each_item| %>
						<div><%= each_item.title %> <span class="float-right"><%= each_item.price %> €</span></div>
						<hr>
					<% end %>
						<article>
						<% if flash[:error].present? %>
							<div id="error_explanation">
								<p><%= flash[:error] %></p>
							</div>
						<% end %>
						<label class="amount float-right">
							<h5>Montant total : &nbsp; <span style="color:grey"><%= @amount / 100%> &euro;</span></h5>
						</label>
					</article>
					<br/><br/><br/>
					

					<script src="https://checkout.stripe.com/checkout.js" class="stripe-button btn-block"
									data-key="<%= Rails.configuration.stripe[:publishable_key]%>"
								data-description="a Cart Order"
						data-amount="<%= @amount %>"
					data-locale="auto"></script>

				<% end %>
				</div>
		</div>