config/routes.rb
Rails.application.routes.draw do
	root "items#index"

	resources :items, only: [:show, :index] do
		resources :cart_items, only: [:create, :destroy]
		resources :image_urls, only: [:create]
	end
	devise_for :users
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	resources :users, only: [:show] do
		resources :carts, only: [:show] do
			resources :orders, only: [:create, :show]
		end
	end
	resources :charges


	scope 'admin', module: 'admin', as: 'admin' do
		resources :items
		resources :orders, only: [:index, :show]
	end



	get "/statics/:static" => "statics#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user
    has_many :cart_items
    has_many :items, through: :cart_items

		def price_sum
			sum = 0
			self.items.each do |each_item|
				sum += each_item.price
			end
			return sum
		end

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :item
    belongs_to :cart

end

app/models/item.rb
class Item < ApplicationRecord    
    validates :title, 
    presence: true
    validates_length_of :title,
    minimum: 5


    validates :description, 
    presence: true
    validates_length_of :description,
    minimum: 10
    
    validates :price, 
    presence: true,
    numericality: {greater_than_or_equal_to: 5}

    validates :image_url, 
    presence: true

    has_many :cart_items, dependent: :destroy
    has_many :carts, through: :cart_items 

		has_many :order_items, dependent: :destroy
		has_many :orders, through: :order_items
    
    has_one_attached :image_url 

		def orders_qty
			qty = self.orders.count
		end

		def self.best_item
			best_item = Item.first
			max_boughts = Item.first.orders_qty
			self.all.each do |each_item|
				if each_item.orders_qty > max_boughts
					max_boughts = each_item.orders_qty
					best_item = each_item
				end
			end
			return best_item
		end

end

app/models/order.rb
class Order < ApplicationRecord
	after_create :command_send
	after_create :admin_send
	belongs_to :user
	has_many :order_items, dependent: :destroy
	has_many :items, through: :order_items

	def command_send
		UserMailer.command_email(self).deliver_now
	end

	def admin_send
		AdminMailer.order_email(self).deliver_now
	end

	def price_sum
		sum = 0
		self.items.each do |each_item|
			sum += each_item.price
		end
		return sum 
	end

	def self.ca
		ca = 0
		Order.all.each do |each_order|
			ca += each_order.price_sum	
		end
		return ca
	end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :order
	belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  after_create :create_cart
  after_create :welcome_send
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one :cart, dependent: :destroy
	has_many :orders


  def create_cart
    @cart = Cart.new(id: self.id, user: self)
    @cart.save
    self.cart = @cart
    self.save
  end

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

	def orders_qty
		qty = self.orders.count
	end

	def self.best_buyer
		best_buyer = User.first
		max_boughts = User.first.orders_qty
		self.all.each do |each_user|
			if each_user.orders_qty > max_boughts
				max_boughts = each_user.orders_qty
				best_buyer = each_user
			end
		end
		return best_buyer
	end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  
  def show
    @cart = Cart.find(params[:id])
		@price_sum = @cart.price_sum 

  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

	def index
		@items = Item.all
	end

	def show
		@item = Item.find(params[:id])
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	
	def show
		puts params
		@user = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/image_urls_helper.rb
module ImageUrlsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/permission_helper.rb
module PermissionHelper
	
	def isAdmin?
		user_signed_in? && current_user.role == 'admin'
	end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class=" footer page-footer font-small blue pt-4 bg-primary text-white mt-5">
  <div class="container-fluid text-center text-md-left text-white">

    <div class="row">
      <div class="col-md-4 mt-md-0 mt-3">
        <h5 class="text-uppercase text-dark">E-Kitty</h5>
        <p>On a tant à partager !</p>
        <a class="text-white" href="/statics/contact">Contact</a>
      </div>
     </div>
 
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="https://mdbootstrap.com/" class = "text-white"> MDBootstrap.com</a>
  </div>
  </div>

</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <% if key == "success" %>
    <div class="alert alert-dismissible alert-success text-center my-2">
      <a href="#" data-dismiss="alert" class="close">×</a>
      <h4 class="alert-heading"> Success ! </h4>
      <p class="text-center"> <%= value %> </p>
    </div>
  <% elsif key == "error" %>
        <div class="alert alert-dismissible alert-danger text-center my-2">
          <a href="#" data-dismiss="alert" class="close">×</a>
          <h4 class="alert-heading"> Error ! </h4>
          <p class="text-center"> <%= value %> </p>
        </div>
  <% elsif key == "notice" %>
      <div class="alert alert-dismissible alert-warning text-center my-2">
        <a href="#" data-dismiss="alert" class="close">×</a>
        <h4 class="alert-heading"> Notice ! </h4>
        <p class="text-center"> <%= value %> </p>
      </div>
  <% elsif key == "alert" %>
      <div class="alert alert-dismissible alert-warning text-center my-2">
        <a href="#" data-dismiss="alert" class="close">×</a>
        <h4 class="alert-heading"> Warning !</h4>
        <p class="text-center"> <%= value %> </p>
      </div>
  <% end %>

<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary pb-2 mb-1">
	<a class="navbar-brand" href="<%= root_path %>">E-Kitty</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>

	<div class="collapse navbar-collapse" id="navbarColor01">
		<ul class="navbar-nav mr-auto">

			<% if user_signed_in? %>

				<li class="nav-item">
					<a class="nav-link" href="<%= user_path(current_user.id) %>">Mon profil</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="<%= destroy_user_session_path %>" data-method="delete">Se déconnecter</a>
				</li>
				<ul class="navbar-nav ml-auto nav-flex-icons">

				</ul>

			<% else %>

				<li class="nav-item">
					<a class="nav-link" href="<%= new_user_registration_path %>">S'Inscrire</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="<%= new_user_session_path %>">Se Connecter</a>
				</li>

			<% end %>

			<li class="nav-item">
				<a class="nav-link" href="/statics/contact">Contact</a>
			</li>

			<% if isAdmin? %>
				<li class="nav-item">
					<%= link_to 'Gestion Items', admin_items_path, class: 'nav-link' %>
				</li>
				<li class="nav-item">
					<%= link_to 'Gestion Commandes', admin_orders_path, class: 'nav-link' %>
				</li>
			<% end %>

		</ul>

		<% if user_signed_in? %>

			<ul class="navbar-nav ml-auto nav-flex-icons">
				<li class="nav-item mr-3 ">
					<a class="nav-link navabar-right text-white" href="<%= user_cart_path(current_user.id, current_user.cart.id) %>">Mon panier<img  class = "panier" src = "/assets/panier.png"></a>
				</li>
				<li class="nav-item avatar">
					<a class="nav-link p-0" href="#">
						<img src="https://anniversaire-celebrite.com/upload/250x333/mireille-mathieu-250.jpg" class="rounded-circle z-depth-0"
																																														alt="avatar image" height="50" width="50">
					</a>
				</li>
			</ul>
		<% end %>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EShop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag "bootstrap"%>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

  </head>
  
    <body class="bg">
   
        <%= render 'layouts/navbar'%>
  <main>
        <div class="container p-0 mt-0">
          <!-- Les Flash d'error -->
          <%= render 'layouts/messages' %>
          <br /> 
          <%= yield %>

        </div>
  </main>
        <%= render 'layouts/footer'%>
  

    </body>

</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>

	<head>
		<title>EShop</title>
		<%= csrf_meta_tags %>
		<%= csp_meta_tag %>

		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
		<%= stylesheet_link_tag "bootstrap"%>
		<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

	</head>

	<body>
		<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
			<a class="navbar-brand" href="<%= root_path %>">E-Kitty</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse" id="navbarColor01">
				<ul class="navbar-nav mr-auto">

					<% if user_signed_in? %>

						<li class="nav-item">
							<a class="nav-link" href="<%= user_path(current_user.id) %>">Mon profil</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="<%= destroy_user_session_path %>" data-method="delete">Se déconnecter</a>
						</li>
						<ul class="navbar-nav ml-auto nav-flex-icons">

						</ul>

					<% else %>

						<li class="nav-item">
							<a class="nav-link" href="<%= new_user_registration_path %>">S'Inscrire</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="<%= new_user_session_path %>">Se Connecter</a>
						</li>

					<% end %>

					<li class="nav-item">
						<a class="nav-link" href="/statics/contact">Contact</a>
					</li>
				</ul>
				<% if user_signed_in? %>

					<ul class="navbar-nav ml-auto nav-flex-icons">
						<li class="nav-item mr-3 ">
							<a class="nav-link navabar-right text-white" href="<%=user_cart_path(current_user.id, current_user.cart.id)%>">Mon panier<img  class = "panier" src = "/assets/panier.png"></a>
						</li>
						<li class="nav-item avatar">
							<a class="nav-link p-0" href="#">
								<img src="https://anniversaire-celebrite.com/upload/250x333/mireille-mathieu-250.jpg" class="rounded-circle z-depth-0"
																																															alt="avatar image" height="50" width="50">
							</a>
						</li>
					</ul>
				<% end %>
			</div>



		</nav>

		<main>

		<div class="container">
			<!-- Les Flash d'error -->
			<%= render 'layouts/messages' %>
			<br />
			<%= yield %>

		</div>
		</main>


		<!-- Footer -->
<footer class=" footer page-footer font-small blue pt-4 bg-primary text-white sticky-bottom mt-5">

  <!-- Footer Links -->
  <div class="container-fluid text-center text-md-left text-white">

    <!-- Grid row -->
    <div class="row">
    <!-- Grid column -->
      <div class="col-md-4 mt-md-0 mt-3">

        <!-- Content -->
        <h5 class="text-uppercase text-dark mb-2">E-Kitty</h5>
        <p>On a tant à partager !</p>
        <a class="text-light text-left" href="/statics/contact">Contact</a>
      </div>        
    
		</div>
  </div>
  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="https://mdbootstrap.com/" class = "text-white"> MDBootstrap.com</a>
  </div>

</footer>


	</body>
</html>